### ISSUE TITLE
A couple of additions

### ISSUE THREAD

**Issue by neilstuartcraig** [dhamaniasad/HeadlessBrowsers#13]
Hi
Just found your list via the Twitters - nice work! I don't see headless Chromium (https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) or JSDOM (https://github.com/tmpvar/jsdom) and thought you might want to consider adding them?

Cheers

**Comment by dhamaniasad** [comment]
Hi, thanks for the nice words! 
Pull requests for the suggestions would be appreciated!

**Comment by neilstuartcraig** [comment]
Sorry this took so long @dhamaniasad - PR sent, hope it's OK.

**Comment by dhamaniasad** [comment]
@neilstuartcraig Since the PR has been merged, I am closing this issue. Thanks!
