### ISSUE TITLE
The Site is down

### ISSUE THREAD

**Issue by deadcoder0904** [dhamaniasad/HeadlessBrowsers#17]
[http://dhamaniasad.github.io/HeadlessBrowsers](http://dhamaniasad.github.io/HeadlessBrowsers) not working

**Comment by dhamaniasad** [comment]
I'm aware of this, it's a DNS issue. I'll be fixing it soon.

**Comment by dhamaniasad** [comment]
Sorry I forgot to update this issue. The site should be back up so I'll go ahead and close this issue now.
