### ISSUE TITLE
Add column for "how like a real browser" (standards-compliant, etc) it is?

### ISSUE THREAD

**Issue by jaredly** [dhamaniasad/HeadlessBrowsers#24]
Many of these are just "emulating" a browser to more or lesser extent, and some of them actually use the rendering engines of full standards-compliant browsers.

**Comment by dhamaniasad** [comment]
PRs are welcome :)

**Comment by watsoncj** [comment]
Great idea. Breaking out which browser APIs are implemented seems useful. Phantom for example is missing getUserMedia.

**Comment by dhamaniasad** [comment]
@watsoncj Would you be willing to add those things to this list, like how caniuse does? It would be very time consuming to do this.

**Comment by tuxayo** [comment]
A more minimalist starting objective would be a column that indicates if it executes JS or not.

**Comment by jaredly** [comment]
Actually, instead of a column, how about splitting into sections?

- real browser engine
- faked browser engine
- other

**Comment by dhamaniasad** [comment]
That works! Thanks for the PR, I'll close this issue now!

**Comment by tuxayo** [comment]
> Actually, instead of a column, how about splitting into sections?

Great, it would allow to have specific columns for real browsers to detail the engine, version, screenshot support, etc. Without polluting the faked/limited browser engines/emulators
