### ISSUE TITLE
Listing which of these browsers are actually headless would be a great addition!

### ISSUE THREAD

**Issue by fake-name** [dhamaniasad/HeadlessBrowsers#34]
Basically, some of these browsers (`nightmare` comes to mind) use electron as their runtime, and [electron requires a working X11 install](https://github.com/segmentio/nightmare/issues/224)!

Personally, I think if a browser requires X to be installed, it's not *really* headless, but in any event, this is a critical distinction for many use cases (I do a bit of browser automation, **entirely** in environments that don't have any X install whatsoever).

If a "headless" browser requires X and `xvfb`, at that point you might as well just run full chromium or firefox with webdriver or similar.

It'd be nice to disambiguate between "headless", as in "doesn't open a visible window" and actually *headless*, as in has no requirement for a framebuffer or X11/etc...

**Comment by thepont** [comment]
Also nightmare here is listed as a lib for controlling PhantomJS, it used to be, but this is now incorrect and as you said it also now requires X11 due to using electron.

**Comment by dhamaniasad** [comment]
We have close to a hundred projects listed here, so this could take a while. PRs are welcome and encouraged :)

**Comment by fake-name** [comment]
I wasn't sure what the goal of this list was, so I didn't want to start creating pull requests without actually talking to someone first.

**Comment by dhamaniasad** [comment]
This list is meant to be a list of all headless browsers in existence, and we'd rather include projects than not, even if part of the criteria for "headless" is not met. But we're happy to classify these projects as such :)

**Comment by fake-name** [comment]
Ok. My concern was mostly releated to how "headless" is defined, and the project scope.

If I can get some time, I'll PR some stuff.

**Comment by dhamaniasad** [comment]
We can define headless as whether or not the project has X related dependencies. I'll get started on going through projects and adding the distinction to the list. PRs are welcome and appreciated! :)

**Comment by dhamaniasad** [comment]
Browsers are now categorized by driver type.
