### ISSUE TITLE
Chrome now has headless mode

### ISSUE THREAD

**Issue by ngbrown** [dhamaniasad/HeadlessBrowsers#37]
Chrome has a headless mode now in Linux/macOS with version 59 released, and will be headless on Windows with version 60.

https://developers.google.com/web/updates/2017/04/headless-chrome
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

**Comment by kensoh** [comment]
Thanks @ngbrown , wanted to add that I can run headless on Windows with v59, just that for v59 it seems to run with a minimized black screen, maybe as a dummy framebuffer.

**Comment by dhamaniasad** [comment]
Headless Chrome is in the list, I'm closing this issue now. Thanks!
