### ISSUE TITLE
dalekjs and phantomjs not actively maintained

### ISSUE THREAD

**Issue by brutalcrozt** [dhamaniasad/HeadlessBrowsers#44]
Firstly thanks for your list, it really help.

1.  as [dalekjs readme](https://github.com/dalekjs/dalek) it say no longer maintained and now it pointing to [testCafe web](https://devexpress.github.io/testcafe/) [testCafe repo](https://github.com/DevExpress/testcafe).
>  testCafe mainly use typescript

2. Sadly phantom seems will not in active state as [maintainer Announcement](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE).

Before make a PR i like to ask, in my opinion it's good to have an additional info on the list. The main usage of the headlessbrowser. AFAIK the `dalekjs` and `testCafe` used to the web page, and the phantomjs have more wide usage. 

I need the any opinion on this, hopefully we can restructure the list to have an additional info. :smile:

**Comment by dhamaniasad** [comment]
Sad to see PhantomJS go unmaintained, but I see the point and I also see a lot of people already moving on to headless Chrome based solutions, so I'm not surprised. We do not want to remove these items from the list, adding an "unmaintained" label will be the best solution for now.

**Comment by dhamaniasad** [comment]
[Unmaintained label was added to PhantomJS](https://github.com/dhamaniasad/HeadlessBrowsers/commit/40847bf0c01c0bfab3cd1cea85e6c60d15f06c8d)

**Comment by rococode** [comment]
It may be worth linking google groups announcement at the "Unmaintained" tag, since it's not clear from the PhantomJS  website or repo that it's actually not under active development anymore

**Comment by dhamaniasad** [comment]
Thanks for the suggestion @rococode!

**Comment by hamza765** [comment]
@dhamaniasad There is currently a developer maintaining PhantomJS. He's made a lot of fixes over the past month.

**Comment by dhamaniasad** [comment]
@hamza765 Interesting. I'll merge the PR marking it as maintained again if you open one.
