### ISSUE TITLE
pyppeteer

### ISSUE THREAD

**Issue by stolati** [dhamaniasad/HeadlessBrowsers#56]
Can someone add pyppeteer ? 
https://github.com/miyakogi/pyppeteer

It's a port of puppeteer in python. Seems to be dead but still usable.

**Comment by dhamaniasad** [comment]
Wow this looks really cool! @stolati I'm happy to accept a PR for this, if you want to make one.

**Comment by dhamaniasad** [comment]
@stolati Will you be making a PR for this?
