### ISSUE TITLE
Wendigo

### ISSUE THREAD

**Issue by angrykoala** [dhamaniasad/HeadlessBrowsers#62]
I've been working on [Wendigo](https://github.com/angrykoala/wendigo) a Puppeteer wrapper to make testing easier.

I wanted to know if it was suitable for this list, as it is not a HeadlessBrowser itself, but a wrapper of one.

**Comment by clach04** [comment]
@angrykoala 👍 , I recommend opening a PR

**Comment by dhamaniasad** [comment]
Merged!
