### ISSUE TITLE
Add performance measurements

### ISSUE THREAD

**Issue by mvrozanti** [dhamaniasad/HeadlessBrowsers#64]
Although defining peformance tests is a hard task, I think it's one of the most useful information from which one to choose and would be a nice addition to this repo

**Comment by dhamaniasad** [comment]
I think that's not feasible. There are different runtimes, browser engines, DOM parsers, languages, JS engines, network conditions, etc. There's a lot of factors that will play a role in the performance of any item on the list. There's tests like https://browserbench.org but they will not run on all the browsers in the list.

Also I don't think performance is the most important metric. The most important metrics will be how much control the browser engine gives you, how accurately it parses the DOM, how close it is to a real browser, does it let you execute arbitrary JS on the page, etc. 

Browsers get updated regularly and the performance metrics keep changing (think the release of Firefox Quantum). So we would need to track new releases and run new benchmarks for all these browsers.

To top all that off, there are currently **75** items on the list, creating benchmarks for all of them would be a monumental task, and expensive to run. 

Marking this issue as closed.

**Comment by mvrozanti** [comment]
Understandable have a nice day
