### ISSUE TITLE
What would be good alternatives for the "puppeteer"?   He is spending a lot of resources

### ISSUE THREAD

**Issue by EwertonDutra** [dhamaniasad/HeadlessBrowsers#74]
Hi,
From the list options
What would be good alternatives for the "puppeteer"?

**I basically need two things:**
**Set the agent and wait for the site to load completely!**

```
await page.setUserAgent ('Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 61.0.3163.100 Safari / 537.36');
await page.goto ('https://www.site.org', {
         waitUntil: 'networkidle0',
});
```

But the "puppeteer" is spending a lot of resources 😅 
Thanks in advance!

**Comment by dhamaniasad** [comment]
If you need to execute JS on the page, you will need to use a heavyweight browser engine which will take up resources. Maybe you can try the Firefox backend in Puppeteer. 

The performance characteristics of the listed browsers are not tracked so you'll have to try the listed options for your language to know what works best for your use case.

**Comment by EwertonDutra** [comment]
@dhamaniasad Thanks

![2021-04-12](https://user-images.githubusercontent.com/13201575/114424025-1f6f9600-9b8e-11eb-94a9-16cd26661736.png)

For those who are researching the same question.
For the tests here in the list options:
Everyone, as well commented, will use an engine (browser or similar)
The increase in resources was mainly in the CPU (about 10%), of course, there is also network consumption and so on.
See the difference in the image at the beginning without the script running and then with it running.

**At least for now, let's keep it the way it is.**
